// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbHk-lHu2Y2GIXeKRZSt77xAOApRPU3A',
    appId: '1:163262491646:web:faf91acd8356c5f157eeaf',
    messagingSenderId: '163262491646',
    projectId: 'fastimmo-e3421',
    authDomain: 'fastimmo-e3421.firebaseapp.com',
    storageBucket: 'fastimmo-e3421.appspot.com',
    measurementId: 'G-0K5F22S2Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2M8-0XAponMijt7yTdti4GiKKvaFbRug',
    appId: '1:163262491646:android:05f59e978d4eaaa557eeaf',
    messagingSenderId: '163262491646',
    projectId: 'fastimmo-e3421',
    storageBucket: 'fastimmo-e3421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVfLOVdIiXaG5YAzMR0uxM9WIO_aLqHY',
    appId: '1:163262491646:ios:d9113396d5d785ac57eeaf',
    messagingSenderId: '163262491646',
    projectId: 'fastimmo-e3421',
    storageBucket: 'fastimmo-e3421.appspot.com',
    iosBundleId: 'com.example.fastImmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVfLOVdIiXaG5YAzMR0uxM9WIO_aLqHY',
    appId: '1:163262491646:ios:d9113396d5d785ac57eeaf',
    messagingSenderId: '163262491646',
    projectId: 'fastimmo-e3421',
    storageBucket: 'fastimmo-e3421.appspot.com',
    iosBundleId: 'com.example.fastImmo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbHk-lHu2Y2GIXeKRZSt77xAOApRPU3A',
    appId: '1:163262491646:web:c46661ade57410c057eeaf',
    messagingSenderId: '163262491646',
    projectId: 'fastimmo-e3421',
    authDomain: 'fastimmo-e3421.firebaseapp.com',
    storageBucket: 'fastimmo-e3421.appspot.com',
    measurementId: 'G-9XJK06EEYS',
  );
}
